add-sign-in
CHI-internship/admin-dashboard pull request #1
Opened 2022-11-01 20:04 UTC by Ecne26

2022-11-02 21:10 UTC, lerik1408 approved these changes

2022-11-02 21:11 UTC, lerik1408 approved these changes
Good Job!
BTW you have conflicting files

2022-11-03 09:31 UTC, BillyAleks requested changes
Thank you, please check the comments. Remove React imports along your changes. And consider using Yup and Formik for form hanling and validation.

2022-11-07 09:03 UTC, lerik1408 reviewed
GJ, but you have conflict

2022-11-07 09:56 UTC, BillyAleks approved these changes
All is good, just consider moving validation to separate modules.

2022-11-07 09:56 UTC, BillyAleks commented on src/components/ChangePassword.js
> +    const validationSchema = yup.object({
I would recommend to write validation schema in separate module

2022-11-07 11:24 UTC, merged