Feature/volunteers activation
CHI-internship/admin-dashboard pull request #4
Opened 2022-11-28 09:58 UTC by pavlokolodka

https://trello.com/c/ND4SotxV

2022-11-28 10:14 UTC, pavlokolodka commented
⚠️ Merge with https://github.com/CHI-internship/KraudDonate-Service/pull/45

2022-11-29 08:32 UTC, RamboUA requested changes
Thank you, please check the comments

2022-11-29 08:32 UTC, RamboUA commented on src/api/admin.api.js
> +    const requests = await axiosInstance
return it directly without await
```suggestion
    return axiosInstance
```

2022-11-29 08:32 UTC, RamboUA commented on src/api/admin.api.js
> +    const request = await axiosInstance
same

2022-11-29 08:32 UTC, RamboUA commented on src/api/admin.api.js
> +  async approveRequest(userId, status, message = null) {
same

2022-11-29 08:32 UTC, RamboUA commented on src/components/Request.js
> +  return (
Something wrong with indents, please check hierarchy

2022-11-29 08:32 UTC, RamboUA commented on src/components/Request.js
> +  return (
And remove blank lines, please

2022-11-29 08:32 UTC, RamboUA commented on src/components/Request.js
> +      onClick={async () => {
Let's move this handler to a function outside

2022-11-29 08:32 UTC, RamboUA commented on src/components/Request.js
> +      onClick={async () => {
Same

2022-11-29 08:32 UTC, RamboUA commented on src/components/Requests.js
> +const getRequest = async (id) => {
```suggestion
const getRequest = async (id) =>  adminService.getVolunteerRequest(id);
```

2022-11-29 08:32 UTC, RamboUA commented on src/components/Requests.js
> +  return (
Please fix indents hierarchically  and move onClick handlers to a function outside

2022-11-29 11:03 UTC, RamboUA requested changes

2022-11-29 11:03 UTC, RamboUA commented on src/components/Requests.js
> +    )
```suggestion
    )}
```
Move it to single line, please

2022-11-29 11:03 UTC, RamboUA commented on src/components/SignIn.js
> +            await adminService.login(values)
I think async/await is not necessary here. Check it please

2022-11-29 11:03 UTC, RamboUA commented on src/components/Requests.js
> +            <Button size="small" onClick={async () => await handleApprove(element.id)}>
should work without async/await

2022-11-29 13:18 UTC, merged