Feature/admin interface
CHI-internship/admin-dashboard pull request #5
Opened 2022-12-05 21:42 UTC by TanyaDovzhenko

2022-12-07 16:26 UTC, lerik1408 approved these changes
👍🏻

2022-12-08 07:59 UTC, RamboUA requested changes
Great job. Please check the comments below:

2022-12-08 07:59 UTC, RamboUA commented on src/components/header/Header.js
> +import React, { useEffect, useState } from 'react';
can you add please here useContext from above?
And please add a rule to linter to check if there are same import directories to warn

2022-12-08 07:59 UTC, RamboUA commented on src/components/header/Header.js
> +    useEffect(() => { if (localStorage.getItem('token')) setAuthorized(true) }, [])
that's to complicated to read.
```suggestion
    useEffect(() => {
       if (localStorage.getItem('token')) setAuthorized(true);
     }, [])
```

2022-12-08 07:59 UTC, RamboUA commented on src/components/requests/RequestCard/RequestCard.js
> +
please remove blank line, or return directly JSX here

2022-12-08 07:59 UTC, RamboUA commented on src/components/requests/RequestPage/RequestPage.js
> +
Extra blank line

2022-12-08 07:59 UTC, RamboUA commented on src/components/requests/RequestPage/RequestPage.js
> +
Can we add this check to linter as well, please?

2022-12-08 07:59 UTC, RamboUA commented on src/components/requests/RequestPage/RequestPage.js
> +      await adminService.getVolunteerRequest(+id).then(data => setRequest(data))
You can simply return the promise.
Maybe let's move getRequest from inside to outside of useEffect, what do you think?

2022-12-08 07:59 UTC, RamboUA commented on src/components/requests/RequestPage/RequestPage.js
> +            <iframe src={"https://docs.google.com/gview?url=" + request.document + "&embedded=true"}>
Can we use a single tag, if nothing is inside?

2022-12-08 07:59 UTC, RamboUA commented on src/components/requests/RequestPage/RequestPage.js
> +            </div>
same

2022-12-08 07:59 UTC, RamboUA commented on src/context/request.context.js
> +        await adminService.getVolunteersRequests()
just return it

2022-12-08 07:59 UTC, RamboUA commented on src/images/arrow.svg
> +<?xml version="1.0" encoding="iso-8859-1"?>
no need

2022-12-08 07:59 UTC, RamboUA commented on src/images/arrow.svg
> +<!-- Generator: Adobe Illustrator 19.0.0, SVG Export Plug-In . SVG Version: 6.00 Build 0)  -->
no need

2022-12-08 07:59 UTC, RamboUA commented on src/images/arrow.svg
> +<svg version="1.1" id="Capa_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px"
better add properties: width: "1em", height: "1em" and fill: "currentColor"

2022-12-08 07:59 UTC, RamboUA commented on src/images/arrow.svg
> +<linearGradient id="SVGID_1_" gradientUnits="userSpaceOnUse" x1="-45.6831" y1="642.2841" x2="-25.8849" y2="633.0515" gradientTransform="matrix(21.3333 0 0 -21.3333 996.3579 13791.6406)">
can you check how the picture will change if we delete this tag?

2022-12-08 07:59 UTC, RamboUA commented on src/images/arrow.svg
> +<path style="fill:url(#SVGID_1_);" d="M255.999,384.004c-2.656,0-5.313-0.99-7.375-2.958L3.29,146.379
I think better is to remove "style" attribute and add "fill" attribute, with  "currentColor" value

2022-12-08 07:59 UTC, RamboUA commented on src/images/arrow.svg
> +<g>
please remove this empty tags

2022-12-08 07:59 UTC, RamboUA commented on src/images/close.svg
> +<?xml version="1.0" ?><svg height="48" viewBox="0 0 48 48" width="48" xmlns="http://www.w3.org/2000/svg"><path d="M38 12.83l-2.83-2.83-11.17 11.17-11.17-11.17-2.83 2.83 11.17 11.17-11.17 11.17 2.83 2
could you please do the same, with width, height, fill properties?

2022-12-08 07:59 UTC, RamboUA commented on src/images/download.svg
> +<?xml version="1.0" encoding="iso-8859-1"?>
Please apply changes required from the previous comment

2022-12-08 07:59 UTC, RamboUA commented on src/images/logout.icon.svg
> +<?xml version="1.0" encoding="iso-8859-1"?>
And here

2022-12-09 09:18 UTC, RamboUA requested changes
That's great. Just check a few comments. And try to rework a little bit some svgs, due to comment that I left. To make it looks perfect.

2022-12-09 09:18 UTC, RamboUA commented on src/components/header/Header.js
> +        </AppBar >
why does this space had appeared?

2022-12-09 09:18 UTC, RamboUA commented on src/components/notification/Notification.jsx
> +    timer.current = setTimeout(() => ref.current.style.display = "none", 30000);
What if this timer will not finish and we will unmount this component?
You will see an error in console browser.
To avoid it - you have to use useEffect and clearTimeout(if timer exists) in a return statement of useEffect.

2022-12-09 09:18 UTC, RamboUA commented on src/components/requests/RequestPage/RequestPage.js
> +    await adminService.getVolunteerRequest(+id).then(data => setRequest(data))
no need for await

2022-12-09 09:18 UTC, RamboUA commented on src/images/close.svg
> +<path d="M0 0h48v48h-48z" fill="none"/></svg>
not a big deal, but if you could keep a structure hierarchy - would be even more great

2022-12-09 09:18 UTC, RamboUA commented on src/images/download.svg
> +<g>
I think this <g> tags are not necessary as well for this scenario.
Could you check this and take a look if it's removal changes something.

2022-12-09 13:57 UTC, RamboUA approved these changes
Great job

2022-12-09 13:57 UTC, RamboUA commented on src/images/download.svg
> +</g>
even this is probably not necessary but I am not sure. Check it please before merge.

2022-12-09 13:57 UTC, RamboUA commented on src/images/logout.icon.svg
> +<g>
and here

2022-12-10 21:49 UTC, merged